### ISSUE TITLE
Gnome 40 update colors inconsistency

### ISSUE THREAD

**Issue by TROMsite** [vinceliuice/vimix-gtk-themes#208]
There are color inconsistencies with the last update. The main colors were the ones seen in Nautilus in the image (the file manager):
![image](https://user-images.githubusercontent.com/38043315/115998852-91fa6000-a5e9-11eb-816b-e0360f71fd90.png)
And now they changed to a brownish color. Was this intentional?

**Comment by vinceliuice** [comment]
This time I want to try the dark gray that matches the primary theme color, so I mixed a little primary theme color into the dark gray, This is an tentative adjustment, If most users don't like this change, I can change it back

**Comment by TROMsite** [comment]
No, it looks fine. But the previous color scheme was quite unique. I really liked it. Dark-grey is what most themes use nowadays. I "vote" for using the original color scheme :D.

**Comment by vinceliuice** [comment]
Maybe I should add this as a option in install.sh

**Comment by TROMsite** [comment]
Why not keep the original colors and add a new flavor "Dark Grey"?

**Comment by vinceliuice** [comment]
No problem!

**Comment by TROMsite** [comment]
So you plan to revert back to the original colors and add a new color into the mix, the dark grey?

**Comment by vinceliuice** [comment]
Yes, make the mix dark grey version as a install option, original as the default one

**Comment by TROMsite** [comment]
Awesome! Thank you!

**Comment by Raubion** [comment]
Thanks for updating! Making my favourite theme on Linux ready for the next age. 
However, not a huge fan of the different colour variations. Always really liked the blueish grey of Vimix with Beryl and Doder. There was already a difference in shade of grey with Vimix Dark regular and Ruby compared to Doder, Beryl and Amethyst, right? Maybe you could also make regular Vimix dark available in the blueish grey variant?
And now that I'm writing this, there may be people who would want the Ruby in the blueish gray or the Beryl in the dark gray. So just to be sure, it would be an option to make them all available in all the different combinations? So people can pick what variation combination they like best.

**Comment by vinceliuice** [comment]
No problem! I'll add this option

**Comment by Raubion** [comment]
Hello,

Thanks for regularly updating the theme. Maybe I've missed something, but in my above comment I suggested making the regular grey theme available in the color scheme of the doder/beryl. You commented you'd add this option, but we're now several versions up and I can't seem to find this. What I mean is this: the bar and background in the grey version are the color 363636 and 282828 whereas the beryl and doder versions are 36383c and 292b2e. Have you added this and can't I find it, or is this not present? Is that an idea you'd be willing to implement?

And on an unrelated note (I could open a separate issue if you prefer that): your Fluent theme has the option to add rounded corners in install.sh. Since this is also the default of Gnome 40, it would be amazing to see this in Vimix as well. Is that something you'd be willing to add?

**Comment by vinceliuice** [comment]
Sorry, forget about this, I'll add this right now, just wait some time

**Comment by vinceliuice** [comment]
Now it's OK, you can run `./install.sh -tweaks mix -a` to install  mix dark grey color versions

**Comment by Raubion** [comment]
You're the best, thanks. I'll check it out with the new release!

**Comment by vinceliuice** [comment]
You are welcome!
