### ISSUE TITLE
libreoffice compatibility/dialog box appearance

### ISSUE THREAD

**Issue by jwhendy** [vinceliuice/vimix-gtk-themes#25]
Have you encountered any issues with libreoffice compatibility and this theme? I've been using it for some time on arch linux with openbox, and I get very different dialog box appearances between LO and other applications. I'm currently using the VimixLight-Laptop variant, and installed via the arch linux [AUR package](https://aur.archlinux.org/packages/vimix-gtk-themes-git/).

geeqie: 
![geeqie](https://cloud.githubusercontent.com/assets/379357/25728550/7463e628-30f5-11e7-98a5-397cb6343abc.png)

gimp:
![gimp](https://cloud.githubusercontent.com/assets/379357/25728558/7e5f0cfc-30f5-11e7-8a2a-b29cc93ba863.png)

libreoffice:
![libreoffice-gtk3](https://cloud.githubusercontent.com/assets/379357/25728561/82ead846-30f5-11e7-97f5-063859215aca.png)

Some other experiments I tried are [here](http://imgur.com/a/q9lm0).

I'm trying to understand if this is a libreoffice bug, or some bit of incompatibility with a gtk expectation/requirement. I had similar oddities when gtk 3.20 first came out as very few themes were fully compatible with it. My first observance was with `pavucontrol`; if a theme wasn't 3.20 compliant the volume bars/sliders wouldn't appear at all or would be all messed up. Yours works with it, so perhaps it's libreoffice's issue?

If nothing else, maybe there's some fallback behavior required, as Adwaita looks consistent but vimix, a theme generated with [oomox](https://github.com/actionless/oomox), and [flat-plat-blue](https://github.com/peterychuang/Flat-Plat-Blue) are all having the same inconsistent behavior.

Thanks for taking a look.

**Comment by twidxuga** [comment]
+1 on this issue, tested in two separate installations of Ubuntu Gnome.

**Comment by jwhendy** [comment]
The comment reminded me to post my current workaround.

```
cat ~/.bash_profile
SAL_USE_VCLPLUGIN=gtk; export SAL_USE_VCLPLUGIN
```

**Comment by jwhendy** [comment]
@vinceliuice any comment on closing? I can still reproduce this.

**Comment by vinceliuice** [comment]
Sorry about this，because libreoffice use the gtk3 theme engine, but it does not fully support the gtk3 theme engine specification, so many effects do not show up, if you want the same effect, it is recommended that you uninstall libreoffice-gtk3 butinstall libreoffice-gtk2 and libreoffice-gtk, Then libreoffice and gimp other gtk2 softwares can use a unified gtk2 theme.
----------------
Here is the way to do if you are using ubuntu or other debian based system：
**sudo apt autoremove --purge libreoffice-gtk3
sudo apt install libreoffice-gtk libreoffice-gtk2**
