### ISSUE TITLE
red squares

### ISSUE THREAD

**Issue by cybbro** [vinceliuice/vimix-gtk-themes#29]
So as title says I get weird red squares where checkbox should be. How can I fix this? I'm using gnome 3.24.2 on Ubuntu Gnome 17.04

[image 1](https://www.photobox.co.uk/my/photo/full?photo_id=21730112078)
[image 2](https://www.photobox.co.uk/my/photo/full?photo_id=21730111672)

**Comment by biggles5107** [comment]
Try installing the theme as a normal user. This is due to a weird permission issue with the installer, where all the asset files are unreadable by users other than root if you do a system-wide installation.

**Comment by robfrawley** [comment]
> This is due to a weird permission issue with the installer, where all the asset files are unreadable by users other than root if you do a system-wide installation.

@biggles5107 That most definitely *should not* be the case. I use the system-wide installer regularly (whenever there is a new commit pushed to the repository) and have never experience that issue. Otherwise, if this is an identified issue, then a PR correcting it would be the resolution, not ignore the system-wide installer.

@cybbro The images you linked to do not work for me (perhaps due to my locale?). You realize you can insert images directly into GitHub issues, right? Just drag the image into the "comment" box when you are typing a reply, or click "selecting them" below the comment box where it says *"Attach files by dragging & dropping, selecting them, or pasting from the clipboard."* If you want to post the images again directly in the GitHub comment I'd be happy to take a look as well.

**Comment by cybbro** [comment]
Replaying quite late, sorry for that, but yes it works now, when I installed it as a regular user instead of root, thank you.
